language: node_js
node_js:
  - "8"

branches:
  only:
  - master

install:
  - npm install
  - npm run generate

script:
- echo "skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master